#include "DatabaseInitializer.h"


DatabaseInitializer::DatabaseInitializer(PostgreSqlConnectionPool &connection,ILogger& logger)
    :m_connection(connection),m_logger(logger){
    Initialize();
}

void DatabaseInitializer::Initialize()
{
    //ALTER TABLE trades ALTER COLUMN trade_id ADD GENERATED BY DEFAULT AS IDENTITY;
    try{        
        auto conn=m_connection.Acquire();
        pqxx::work tx(*conn);
        tx.exec(R"(
            create table if not exists trades(
                trade_id BIGINT PRIMARY KEY,
                symbol VARCHAR(32) NOT NULL,
                side INTEGER NOT NULL,
                quantity BIGINT NOT NULL,
                price DOUBLE PRECISION NOT NULL,
                timestamp BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT
            );
        )");
        tx.exec(R"(
            create table if not exists positions(
                symbol VARCHAR(32) PRIMARY KEY,
                quantity BIGINT NOT NULL,
                avg_price DOUBLE PRECISION NOT NULL,
                market_price DOUBLE PRECISION NOT NULL,
                realized_pnl DOUBLE PRECISION NOT NULL
            );
        )");
        tx.exec(R"(
            CREATE TABLE IF NOT EXISTS trade_audit
            (
                id BIGSERIAL PRIMARY KEY,
                trade_id BIGINT,
                event_type VARCHAR(64),
                payload JSONB,                    
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
        )");

        tx.exec(R"(
            CREATE TABLE IF NOT EXISTS risk_rules
            (
                rule_id BIGSERIAL PRIMARY KEY,                    
                rule_type VARCHAR(64) NOT NULL,                    
                symbol VARCHAR(32),                    
                rule_value DOUBLE PRECISION NOT NULL,                    
                enabled BOOLEAN NOT NULL DEFAULT TRUE,                    
                description TEXT,                    
                updated_at TIMESTAMP DEFAULT NOW()
            );
        )");
        tx.exec(R"(
            CREATE TABLE IF NOT EXISTS risk_violations(
                violation_id BIGSERIAL PRIMARY KEY,
                timestamp BIGINT NOT NULL,
                symbol VARCHAR(32),
                violation_type VARCHAR(64),
                message TEXT NOT NULL,
                trade_json JSONB,
                created_at TIMESTAMP DEFAULT NOW()
            );
            CREATE INDEX IF NOT EXISTS idx_risk_violation_symbol ON risk_violations(symbol);
            CREATE INDEX IF NOT EXISTS idx_risk_violation_time ON risk_violations(timestamp);
        )");        

        tx.exec(R"(
            CREATE TABLE IF NOT EXISTS risk_ai_analysis
            (
                analysis_id BIGSERIAL PRIMARY KEY,            
                violation_id BIGINT NOT NULL,            
                analysis TEXT NOT NULL,            
                recommendation TEXT,            
                model_name VARCHAR(64),            
                confidence DOUBLE PRECISION,
                severity DOUBLE PRECISION,            
                created_at TIMESTAMP DEFAULT NOW(),            
                CONSTRAINT fk_violation  FOREIGN KEY(violation_id) REFERENCES risk_violations(violation_id)
            );
            CREATE INDEX IF NOT EXISTS idx_risk_ai_violation ON risk_ai_analysis(violation_id);
        )");
        tx.exec(R"(
               CREATE TABLE IF NOT EXISTS ai_job(
                job_id BIGSERIAL PRIMARY KEY,
                violation_id BIGINT NOT NULL,
            
                status VARCHAR(20) NOT NULL,
                retry_count INT NOT NULL DEFAULT 0,
            
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                started_at TIMESTAMP,
                completed_at TIMESTAMP,            
                error_message TEXT,            
                CONSTRAINT fk_ai_job_violation FOREIGN KEY(violation_id) REFERENCES risk_violations(violation_id)
            );
            CREATE INDEX IF NOT EXISTS idx_ai_job_violation_id ON ai_job(violation_id);
            CREATE INDEX IF NOT EXISTS idx_ai_job_status ON ai_job(status);
        )");

        tx.exec(R"(
            CREATE TABLE IF NOT EXISTS ai_analysis
            (
                analysis_id BIGSERIAL PRIMARY KEY,
                job_id BIGINT NOT NULL,
                violation_id BIGINT NOT NULL,
                model_name VARCHAR(100),
                analysis JSONB NOT NULL,
                processing_time_ms BIGINT,
                created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                CONSTRAINT fk_ai_analysis_job FOREIGN KEY(job_id) REFERENCES ai_job(job_id),                     
                CONSTRAINT fk_ai_analysis_violation FOREIGN KEY(violation_id) REFERENCES risk_violations(violation_id)
            );
            CREATE INDEX IF NOT EXISTS idx_ai_analysis_job ON ai_analysis(job_id);
            CREATE INDEX IF NOT EXISTS idx_ai_analysis_violation ON ai_analysis(violation_id);
            CREATE INDEX IF NOT EXISTS idx_ai_analysis_created ON ai_analysis(created_at);

        )");
        tx.commit();
        m_logger.Info("DB inti successfully");
    }catch(std::exception& ex){
        m_logger.Error(std::format("DB init: exception: {}", ex.what()));
        //throw std::runtime_error(ex.what());
    }
            
}
